Fix username logging on 500 responses. (#754)
* Fix username logging on 500 responses.

A bug causes the server to send no response, such that the client
raised:

```
RemoteProtocolError: Server disconnected without sending a response.
```

instead of returning 500 response. This was a regression
introduced in #750.

Needs test.

Closes #750

* Add comment

* Refine comments

* TST: Reproduce 'Server disconnected without sending a response' in test.

* Update CHANGELOG

* Clean up prints in test

* Refactor so server can be shut down.