Version-lock fastapi
fastapi 0.93.0 causes `tiled serve config` to fail with
RuntimeError: Cannot add middleware after an application has started
error. Version-locking fastapi to 0.89.1 seems to fix the issue.